# playbook.yml
---
- name: Deploy Shiny Server Docker container
  hosts: localhost
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/dar4datascience/A-Shiny-App-X-ways-to-deploy-it.git
        dest: /tmp/shiny-app

    - name: Copy app folder to Shiny Server
      copy:
        src: /tmp/shiny-app/app
        dest: /srv/shiny-server/
        remote_src: yes

    - name: Ensure /ansible directory exists
      file:
        path: /ansible
        state: directory

    - name: Copy Dockerfile for Shiny Server
      copy:
        src: Dockerfile.shiny
        dest: /ansible/Dockerfile.shiny
        remote_src: yes

    - name: Build Shiny Server Docker image
      command: docker build -t shiny-server /ansible
      args:
        chdir: /ansible

    - name: Run Shiny Server Docker container
      docker_container:
        name: shiny-server-container
        image: shiny-server
        state: started
        ports:
          - "3838:3838"
