---
- name: Deploy Shiny Server
  hosts: localhost
  become: yes
  tasks:
    - name: Update package sources
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - git-core
          - libssl-dev
          - libcurl4-gnutls-dev
          - curl
          - libsodium-dev
          - libxml2-dev
          - libicu-dev
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/dar4datascience/A-Shiny-App-X-ways-to-deploy-it.git
        dest: /tmp/shiny-app

    - name: Copy app folder to Shiny Server
      copy:
        src: /tmp/shiny-app/app
        dest: /srv/shiny-server/
        remote_src: yes

    - name: Install R packages
      command: R -e "install.packages(c('plotly', 'forecast', 'jsonlite', 'ggplot2', 'htmltools'), repos='http://cran.rstudio.com/')"

    - name: Change ownership of Shiny Server directory
      file:
        path: /srv/shiny-server/
        owner: shiny
        group: shiny
        recurse: yes

    - name: Ensure Shiny Server is running
      become: yes
      ansible.builtin.service:
        name: shiny-server
        state: started